#!/bin/sh

numlockx
setxkbmap be
setterm -blank 0 -powersave off -powerdown 0
xset -dpms s off

xrdb -merge $HOME/.config/X/Xresources
xsetroot -solid grey

if [ $(hostname) == machine1 ]
then
    # $HOME/.config/arandr-layout.sh
    $HOME/.config/arandr-layout-scaled.sh
    xrandr --output HDMI-1 --scale 1.25x1.25
fi

exec i3 >> $HOME/.local/log/i3 2>&1
